version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      updates:
        patterns:
          - "*"
        update-types:
          - patch
          - minor
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      patches:
        patterns:
          - "*"
        update-types:
          - patch
