version: 2

project_name: mc-router
release:
  github:
    owner: itzg
    name: mc-router
before:
  hooks:
    - go mod download
builds:
  - id: mc-router
    main: ./cmd/mc-router
    binary: mc-router
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0
archives:
  - format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE*
      - README*
dockers_v2:
  - images:
      - "itzg/{{ .ProjectName }}"
      - "ghcr.io/itzg/{{ .ProjectName }}"
    dockerfile: Dockerfile.release  
    tags:
      - "{{ .Version }}"
      - "latest"
    labels:
      org.opencontainers.image.authors: "Geoff Bourne <itzgeoff@gmail.com>"
      org.opencontainers.image.title: "mc-router"
      org.opencontainers.image.description: "Routes Minecraft Java Edition client connections to backend servers based upon the requested server address."
      org.opencontainers.image.source: "{{ .GitURL }}"
      org.opencontainers.image.version: "{{ .Version }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.name: "{{ .ProjectName }}"
changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'
