project_name: mc-router

release:
  github:
    owner: itzg
    name: mc-router

before:
  hooks:
    - go mod download

builds:
  - id: mc-router
    main: ./cmd/mc-router
    binary: mc-router
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
    env:
      - CGO_ENABLED=0

archives:
  - id: tar_gz
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

snapshot:
  name_template: SNAPSHOT-{{ .ShortCommit }}

brews:
  - install: |
      bin.install "mc-router"

dockers:
  # Docker Hub: amd64
  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "itzg/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile.release
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  # Docker Hub: arm64
  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "itzg/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile.release
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  # Docker Hub: arm32v6
  - image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm32v6"
      - "itzg/{{ .ProjectName }}:latest-arm32v6"
    dockerfile: Dockerfile.release
    goarch: arm
    goarm: "6"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  # GHCR: amd64
  - image_templates:
      - "ghcr.io/itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/itzg/{{ .ProjectName }}:latest-amd64"
    dockerfile: Dockerfile.release
    goarch: amd64
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  # GHCR: arm64
  - image_templates:
      - "ghcr.io/itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/itzg/{{ .ProjectName }}:latest-arm64"
    dockerfile: Dockerfile.release
    goarch: arm64
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

  # GHCR: arm32v6
  - image_templates:
      - "ghcr.io/itzg/{{ .ProjectName }}:{{ .Version }}-arm32v6"
      - "ghcr.io/itzg/{{ .ProjectName }}:latest-arm32v6"
    dockerfile: Dockerfile.release
    goarch: arm
    goarm: "6"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"

docker_manifests:
  # Docker Hub combined images
  - name_template: "itzg/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "itzg/{{ .ProjectName }}:{{ .Version }}-arm32v6"
  - name_template: "itzg/{{ .ProjectName }}:latest"
    image_templates:
      - "itzg/{{ .ProjectName }}:latest-amd64"
      - "itzg/{{ .ProjectName }}:latest-arm64"
      - "itzg/{{ .ProjectName }}:latest-arm32v6"

  # GHCR combined images
  - name_template: "ghcr.io/itzg/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/itzg/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/itzg/{{ .ProjectName }}:{{ .Version }}-arm64"
      - "ghcr.io/itzg/{{ .ProjectName }}:{{ .Version }}-arm32v6"
  - name_template: "ghcr.io/itzg/{{ .ProjectName }}:latest"
    image_templates:
      - "ghcr.io/itzg/{{ .ProjectName }}:latest-amd64"
      - "ghcr.io/itzg/{{ .ProjectName }}:latest-arm64"
      - "ghcr.io/itzg/{{ .ProjectName }}:latest-arm32v6"

changelog:
  filters:
    exclude:
      - '^ci:'
      - '^docs:'
      - '^misc:'
      - '^test:'
