FROM alpine AS certs
RUN apk add -U \
    ca-certificates

FROM scratch

ARG TARGETPLATFORM

COPY --from=certs /etc/ssl/certs/ /etc/ssl/certs
COPY $TARGETPLATFORM/mc-router /
ENTRYPOINT ["/mc-router"]
