FROM alpine AS certs
RUN apk add -U \
    ca-certificates

FROM scratch

LABEL org.opencontainers.image.authors="Geoff Bourne <itzgeoff@gmail.com>"
LABEL org.opencontainers.image.title="mc-router"
LABEL org.opencontainers.image.source="https://github.com/itzg/mc-router"

COPY --from=certs /etc/ssl/certs/ /etc/ssl/certs
COPY mc-router /
ENTRYPOINT ["/mc-router"]
