FROM cgr.dev/chainguard/static

ARG TARGETPLATFORM

COPY --from=certs /etc/ssl/certs/ /etc/ssl/certs
COPY --from=certs /usr/share/zoneinfo /usr/share/zoneinfo
COPY $TARGETPLATFORM/mc-router /
ENTRYPOINT ["/mc-router"]
