# nonk8s
apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: mc-router-dev
build:
  artifacts:
  - image: itzg/mc-router-dev
    # https://skaffold.dev/docs/pipeline-stages/builders/ko/
    ko:
      main: ./cmd/mc-router/

manifests:
  rawYaml:
  - docs/k8s-deployment.yaml
deploy:
  kubectl:
