apiVersion: skaffold/v4beta13
kind: Config
metadata:
  name: mc-router
build:
  artifacts:
  - image: itzg/mc-router
    # https://skaffold.dev/docs/pipeline-stages/builders/ko/
    ko:
      main: ./cmd/mc-router/
manifests:
  rawYaml:
  - docs/k8s-deployment.yaml
deploy:
  kubectl:
