services:
  router:
    image: itzg/mc-router
    environment:
      IN_DOCKER: true
      AUTO_SCALE_DOWN: true
      AUTO_SCALE_UP: true
      AUTO_SCALE_DOWN_AFTER: 1m
      AUTO_SCALE_ASLEEP_MOTD: "Server is asleep. Join again to wake it up!"
      DEBUG: true
    ports:
      - "25565:25565"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # Refer to the "User access to docker socket" section in the README
    group_add:
      - "0"

  vanilla:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
    labels:
      mc-router.host: |
        localhost
        127.0.0.2

