services:
  # Isolate root-level access to the docker socket
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    user: root
    environment:
      CONTAINERS: 1
      SERVICES: 1
      POST: 1
      NETWORKS: 1
      TASKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - minecraft

  # ...to be used by other services such as mc-router
  router:
    image: itzg/mc-router
    environment:
      IN_DOCKER_SWARM: "true"
      DOCKER_SOCKET: "tcp://socket-proxy:2375"
      AUTO_SCALE_DOWN: "true"
      AUTO_SCALE_UP: "true"
      AUTO_SCALE_DOWN_AFTER: "1m"
      AUTO_SCALE_ASLEEP_MOTD: "Server is asleep. Join again to wake it up!"
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - target: 25565
        published: 25565
        protocol: tcp
        mode: host
    networks:
      - minecraft

  mcfoobar:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "mc-router.host=foo.host.name,bar.host.name,localhost"
        - "mc-router.network=minecraft" # not required in this case
    volumes:
      - mcfoobardata:/data
    networks:
      - minecraft
    environment:
      EULA: "true"

  mcbaz:
    image: itzg/minecraft-server:latest
    tty: true
    stdin_open: true
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "mc-router.host=baz.host.name"
        - "mc-router.network=minecraft" # required since we are exposing a port
    ports:
      - "25575:25575" # RCON
    volumes:
      - mcbazdata:/data
    networks:
      - minecraft
    environment:
      EULA: "true"

volumes:
  mcbazdata:
  mcfoobardata:


networks:
  minecraft:
    driver: overlay
